fint:
  kafka:
    enable-ssl: false
    default-replicas: 1
    application-id: samtykke-admin-backend
    topic:
      domain-context: fint-core

spring:
  kafka:
    bootstrap-servers: localhost:9092