fint:
  samtykke-admin:
    base-url: https://beta.felleskomponent.no

spring:
  webflux:
    base-path: /consent-admin
  profiles:
    include:
      - kafka

logging:
  level:
    org.apache.kafka: OFF
    no.fintlabs.kafka: OFF
    org.springframework.kafka: OFF
    no.fintlabs: DEBUG