spring:
  webflux:
    base-path: /consentadmin
  profiles:
    include:
      - kafka
      - oauth

logging:
  level:
    org.apache.kafka: OFF
    no.fintlabs.kafka: OFF
    org.springframework.kafka: OFF
    no.fintlabs: DEBUG