spring:
  webflux:
    base-path: /api/samtykke
  profiles:
    include:
      - kafka
      - oauth

springdoc:
  swagger-ui:
    path: /swagger

logging:
  level:
    org.apache.kafka: DEBUG
    no.fintlabs.kafka: DEBUG
    org.springframework.kafka: DEBUG
    no.fintlabs: DEBUG