spring:
  kafka:
    consumer:
      group-id: consumer
  codec:
    max-in-memory-size: 200MB

fint:
  kafka:
    enable-ssl: true
    application-id: samtykke-admin-backend
    topic:
      domain-context: fint-core
