fint:
  org-id: 'fintlabs.no'
  base-url: 'https://api.felleskomponent.no/personvern/samtykke'
  registration-id: 'fint'

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id: ${fint.core.oauth2.client-id}
            client-secret: ${fint.core.oauth2.client-secret}
            provider: fint-idp
            scope: fint-client
