apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../base
commonLabels:
  app.kubernetes.io/name: fint-samtykke-admin-backend
  app.kubernetes.io/instance: fint-samtykke-admin-backend_fintlabs_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: fintlabs.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/url/hostname"
        value: "https://beta.felleskomponent.no"
      - op: replace
        path: "/spec/url/hostname"
        value: "https://beta.felleskomponent.no"
    target:
      kind: Application
      name: fint-samtykke-admin-backend