apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-samtykke-admin-backend
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-samtykke-admin-backend
    app.kubernetes.io/instance: fint-samtykke-admin-backend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  orgId: fintlabs.no
  image: docker/getting-started
  imagePullPolicy: Always
  envFrom:
    - secretRef:
        name: fint-samtykke-admin-backend-kafka
    - secretRef:
        name: fint-samtykke-admin-backend-kafka-certificates
  kafka:
    enabled: true
    acls:
      - topic: '*.fint-core.*'
        permission: admin
  url:
    hostname: replaceUrl
  ingress:
    enabled: true
    basePath: /api
  resources:
    limits:
      memory: "1024Mi"
      cpu: "250m"
    requests:
      memory: "128Mi"
      cpu: "100m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }